define(['jquery'],function($){'use strict';$(function(){var pluginName='accordion',triggerEl='.acc',defaults={speed:250,multiOpen:false,openFirstOnInit:true};function Plugin(element,options){this.$el=$(element);this.$items=this.$el.find('.acc-items');this.$titles=this.$el.find('.acc-title');this.$titleActive=this.$el.find('.acc-title').filter('.active');this.$content=this.$el.find('.acc-content');this.$contentAdditional=this.$el.find('.acc-content-additional');this.dataOptions=this._parseDataOptions(this.$el.data('acc-options'));this.settings=$.extend({},defaults,options,this.dataOptions);this.api={};this._defaults=defaults;this._name=pluginName;this.init();}
Plugin.prototype._parseDataOptions=function(optionString){if(!optionString){return{};}
var options={};var optionArray=optionString.split(';');var typeCheck=function(string){if(typeof string!=='string'){return false;}
var val=$.trim(string);if(val.toLowerCase()==='true'){val=true;}else if(val.toLowerCase()==='false'){val=false;}else if(parseInt(val,10)){val=parseInt(val,10);}
return val;};if(!optionString){return options;}
for(var i=optionArray.length-1;i>=0;i--){var option=optionArray[i].split(':');var prop=typeCheck(option[0]);var val=typeCheck(option[1]);if(prop&&val!==''){options[prop]=val;}}
return options;};Plugin.prototype.init=function(){if(!this.$titleActive.length&&this.settings.openFirstOnInit){this.$titleActive=this.$titles.first();}
this.setMetaData();this.$content.hide();if(this.$contentAdditional.length){this.$contentAdditional.hide();}
this.open(this.$titleActive);this.$titles.on('click.acc',$.proxy(this.toggleStates,this));this.$items.addClass('initialized');};Plugin.prototype.toggleStates=function(e){var $thisTitle=e?$(e.currentTarget):this.$titleActive;if($thisTitle.hasClass('active')){this.close($thisTitle);}else{this.open($thisTitle);}
e.preventDefault();};Plugin.prototype.open=function($thisTitle){var index=$thisTitle.data('csw-index');var $thisContent=this.$content.eq(index);var $thisContentAdditional=this.$contentAdditional.eq(index);$thisTitle.addClass('active');$thisContent.slideDown(this.settings.speed);if(!this.settings.multiOpen){this.$titles.not($thisTitle).removeClass('active');this.$content.not($thisContent).slideUp(this.settings.speed);}
if($thisContentAdditional.length){$thisContentAdditional.slideDown(this.settings.speed);if(!this.settings.multiOpen){this.$contentAdditional.not($thisContentAdditional).slideUp(this.settings.speed);}}};Plugin.prototype.close=function($thisTitle){var index=$thisTitle.data('csw-index');var $thisContent=this.$content.eq(index);var $thisContentAdditional=this.$contentAdditional.eq(index);if(!this.settings.multiOpen){this.$titles.removeClass('active');}
$thisTitle.removeClass('active');$thisContent.slideUp(this.settings.speed);if($thisContentAdditional.length){$thisContentAdditional.slideUp(this.settings.speed);}};Plugin.prototype.setMetaData=function(){this.$titles.each(function(index){$(this).data('csw-index',index);});};$.fn[pluginName]=function(options){var args=arguments;this.each(function(){var $this=$(this);if(!options||typeof options==='object'){if(!$this.data('plugin_'+pluginName)){$this.data('plugin_'+pluginName,new Plugin(this,options));}}else if(typeof options==='string'){var instance=$this.data('plugin_'+pluginName);if(instance.api&&instance.api[options]){instance.api[options].apply(instance,Array.prototype.slice.call(args,1));}}});return this;};$(triggerEl)[pluginName]();});});