define(['jquery','app/color-switcher'],function($){'use strict';$(function(){var Lightbox=function(el,options){var self=this;self.settings=$.extend({},$.lightbox.defaults,options);self.triggerEl=el;self.$container=$('<div/>').addClass('lbx').show();self.$matte=$('<div/>').addClass('lbx-matte');self.$close=$('<div/>').addClass('lbx-close');self.$overlay=$('<div/>').addClass('lbx-overlay');self.$overlayContent=$('<div/>').addClass('lbx-overlay-content');self.$body=$('body');self.$contentWrapper=$('.content-wrapper');self.$openImmediately=self.$contentWrapper.find('.lbx-open-immediately.images');self.myEvents=$({});self.closeTimer='';self.myHelpers=self.helpers();self.myOverlay=self.overlay();self.myTrigger=self.trigger();self.myTrigger.init();};Lightbox.prototype.trigger=function(){var self=this,mod={};mod.init=function(){if(self.settings.openImages){self.myOpenImages=self.openImages();$(document).on('click.lbx-open',self.triggerEl,function(e){self.myOpenImages.init($(e.currentTarget));return false;});$('body').addClass('lbx-open-initialized');if(self.$openImmediately.length){self.myOpenImages.init(self.$openImmediately);self.$openImmediately='';}}
if(self.settings.openVideo){self.$contentWrapper.on('click.lbx-open',self.triggerEl,function(e){self.myOverlay.init($(e.currentTarget).attr('href'));self.$container.addClass('video');return false;});}
if(self.settings.openModal){self.$contentWrapper.on('click.lbx-open',self.triggerEl,function(e){var $this=$(e.currentTarget);var url=$this.attr('href');self.myOverlay.init(false);if($this.data('source')){self.$container.addClass('lbx-wide');}
self.myModal=self.modal();self.myModal.loadModalContent(url,function(data){var $modalContent=$('.lbx-modal-content'),topPos=$modalContent.css('top');if(($modalContent.outerHeight()+80)>$(window).height()){var offsetTop=self.$container.offset().top;self.$container.css('position','absolute').css('top',offsetTop+'px');}else{self.$container.css('position','fixed').css('top',topPos);}
$modalContent.removeClass('loading');$modalContent.find('.csw').colorSwitcher();var $accordion=$modalContent.parent().find('.acc');if($accordion.length){$accordion.removeData('plugin_accordion');$accordion.accordion();}
$modalContent.addClass('lbx-centered');$modalContent.parent().addClass('lbx-reset');$('.lightbox_tab').on('click',function(){$(".lightbox_tab").removeClass("active");$(this).addClass("active");var id=$(this).attr("id");if(id==="surfaces-tab"){$("#measurements-list").hide();$("#surfaces-list").show();}else if(id=="measurements-tab"){$("#surfaces-list").hide();$("#measurements-list").show();}});},$this.data('source'));return false;});}
if(self.settings.openFlyout){self.$overlayContent.on('click.lbx-open',self.triggerEl,function(e){var url=$(e.currentTarget).attr('href');self.myOverlay.init(false);self.myFlyout=self.flyout();self.myFlyout.loadFlyoutContent(url,function(){});return false;});}
if(self.settings.openDialog){self.$body.on('click.lbx-open',self.triggerEl,function(e){var url=$(e.currentTarget).attr('href');self.myOverlay.init(url);self.myDialog=self.openDialog();self.myDialog.init();return false;});}
if(self.settings.openRichText){self.$body.on('click.lbx-open',self.triggerEl,function(e){var url_parts=$(e.currentTarget).attr('href').split('#'),url=url_parts[0]+'?ajax=true'+(url_parts[1]?'#'+url_parts[1]:'');self.myOverlay.init(url);self.$container.addClass('richtext');self.$close.addClass('light');require(['jquery.smoothScrollTo'],function(){self.$container.smoothScrollTo();});return false;});}
if(self.settings.youtube){self.$contentWrapper.on('click.lbx-open',self.triggerEl,function(e){e.preventDefault();var href=$(e.currentTarget).attr('href'),ytID='',pos=href.indexOf('v=');if(pos!=-1){ytID=href.substring(pos+2,pos+13);}
if(ytID!=''){var ytMarkup='<iframe id="ytplayer" type="text/html" width="850" height="480"'+' src="'+document.location.protocol+'//www.youtube.com/embed/'+ytID+'?autoplay=0&controls=1"'+' frameborder="0" />';self.myOverlay.init(false);self.$overlayContent.html(ytMarkup);self.$container.addClass('youtube');}
if(self.settings.prependContent){self.$overlayContent.prepend(self.settings.prependContent.show());}
if(self.settings.appendContent){self.$overlayContent.append(self.settings.appendContent.show());}
return false;});}
if(self.settings.loadProductDetails){self.$container.addClass("msl-lightbox");}};return{init:mod.init};};Lightbox.prototype.helpers=function(){var self=this,mod={};mod.submitAndRefresh=function($form,$target,callback){var url=$form.attr('action')?$form.attr('action'):false;$target.empty().addClass('preloading');$.post(url,$form.serialize(),function($data){$target.removeClass('preloading').html($data);self.myHelpers.requireModules($target);if(callback&&typeof callback==='function'){callback();}});};mod.requireModules=function($target){if($target.find('form select').length){require(['app/selectboxes'],function(){$($target).find('form select').filter(function(){return $(this).hasClass('sbx-no')===false;}).selectboxes();});}
if(!$.favorites){require(['app/favorites']);}
if($target.find('.jmp').length!==0){require(['app/jump-marker']);}
if($target.find('.shr').length!==0){require(['app/social-share'],function(){$target.find('.shr').socialShare();});}
if($target.find('video').length!==0){require(['mediaelementplayer'],function(){$('video').mediaelementplayer({videoWidth:-1,videoHeight:-1,features:['playpause','progress','current','duration','tracks','volume'],timeAndDurationSeparator:'<span> / </span>',videoVolume:'horizontal',success:function(video,video2,mediaelement){var portrait=false,$mediaelement=mediaelement.container.find('.mejs-mediaelement'),$addCtrls=mediaelement.container.parents('.vid-player').find('.mejs-add-to-ctrls');if($addCtrls.length){var $controls=mediaelement.container.find('.mejs-controls');$addCtrls.children().appendTo($controls);$addCtrls.remove();}
function getAspect(){var containerWidth=$mediaelement.width(),containerHeight=$mediaelement.height(),aspect=containerWidth/containerHeight;if(aspect<1.777&&portrait===false){portrait=true;mediaelement.container.addClass('portrait');}else if(aspect>=1.777&&portrait===true){portrait=false;mediaelement.container.removeClass('portrait');}}
getAspect();$(window).resize(getAspect);}});});}
if($target.find('.tie').length!==0){require(['app/tie-slider'],function(){$target.find('.tie').tieSlider();});}};return{submitAndRefresh:mod.submitAndRefresh,requireModules:mod.requireModules};};Lightbox.prototype.openImages=function(){var self=this,mod={};mod.init=function($clickedLink){var url;if(self.$openImmediately.length){url=self.$openImmediately.data('open-url');}else{url=mod.getUrl($clickedLink);}
self.myOverlay.init(url);};mod.getUrl=function($clickedLink){var
urlBase=self.settings.ajaxUrl,urlGroup='group=',urlIds='ids=',urlStartId='start=',urlPressDwn='press_download=',group=$clickedLink.attr('rel'),startId=$clickedLink.data('id'),pressDwn=$clickedLink.data('press-download')||'0',ids=[],$parentContainer=$clickedLink.parents('.swp-item, .frg-related-images'),$context=$parentContainer.length?$parentContainer:$clickedLink.parents('.content-wrapper');$(self.triggerEl,$context).each(function(){if($(this).attr('rel')===group){ids.push($(this).data('id'));}});var max=30;if(ids.length>max){var cur=ids.indexOf(startId),from=cur-5,to=cur-5+max;ids=ids.slice(from>0?from:0,to);}
urlGroup+=group;urlIds+=ids.join(',');urlStartId+=startId;urlPressDwn+=pressDwn;return urlBase+urlGroup+'&'+urlIds+'&'+urlStartId+'&'+urlPressDwn;};return{init:mod.init};};Lightbox.prototype.openDialog=function(){var self=this,mod={};mod.init=function(){self.$container.addClass('dialog');self.$overlayContent.on('click.lbx-overlay','.lbx-cancel',self.myOverlay.close);self.$overlayContent.on('click.lbx-overlay','.do_submit-form',function(){self.myHelpers.submitAndRefresh($('#alb-lbx-form'),self.$overlayContent,function(){if(self.$overlayContent.find('.do_fade-out').length){self.$container.one('click.lbx-overlay',self.myOverlay.close);self.closeTimer=setTimeout(function(){self.myOverlay.close();},self.settings.dialogCloseTime);}
if(self.$overlayContent.find('.do_redirect').length){self.myEvents.one('LBX_CLOSE',function(){var url=self.$overlayContent.find('.do_redirect').data('redirect');document.location.href=url;});}
if(self.$overlayContent.find('.do_reload').length){self.myEvents.one('LBX_CLOSE',function(){document.location.reload();});}});return false;});};return{init:mod.init};};Lightbox.prototype.overlay=function(){var self=this,mod={};mod.init=function(url){self.$container.removeClass('lbx-wide');self.$overlay.append(self.$overlayContent).append(self.$close);self.$container.append(self.$matte).append(self.$overlay).prependTo(self.settings.lightboxTarget);clearTimeout(self.closeTimer);window.setTimeout(function(){self.$container.addClass('active');if(!Modernizr.csstransitions){self.$container.hide().fadeIn();}},0);self.$close.on('click.lbx-overlay',mod.close);if(self.settings.closeOnBlur){self.$matte.on('click.lbx-overlay',mod.close);}
$(document).one('keyup.lbx-overlay',function(e){if(e.keyCode===27){mod.close();}});if(url===false){return;}
mod.loadAjaxContent(url,self.$overlayContent,function(){self.myHelpers.requireModules(self.$overlayContent);if(self.$overlayContent.find('.lbx-open.modal').length){self.myModal=self.modal();self.myModal.init();}
if(self.$overlayContent.find('.lbx-open.flyout').length){self.myFlyout=self.flyout();self.myFlyout.init();self.myModal=self.modal();self.myModal.init();}});mod.calculateHeight();return false;};mod.calculateHeight=function(){var baseWidth=self.settings.baseWidth,baseHeight=self.settings.baseHeight,ratio=Math.abs(baseWidth/baseHeight),lbxHeight=self.$overlayContent.height(),windowHeight=$(window).height(),windowWidth=$(window).width(),newLbxHeight;if(windowWidth>windowHeight){newLbxHeight=lbxHeight;}else{newLbxHeight=lbxHeight*ratio;}
self.$overlay.height(Math.floor(newLbxHeight));};mod.close=function(){if(self.myModal){self.myModal.close();}
self.$container.removeClass('active');$('.lbx').remove();$(document).off('.lbx-overlay');self.myEvents.trigger('LBX_CLOSE');};mod.addOverlayContent=function($dom){self.$overlayContent.append($dom);};mod.loadAjaxContent=function(url,$target,callback,$source){$target.empty();$.get(url,function(data){if($source){$target.html($(data).find($source).html());}else{$target.html(data);}
if(callback&&typeof callback==='function'){callback();}});};return{init:mod.init,loadContent:mod.loadAjaxContent,close:mod.close};};Lightbox.prototype.modal=function(){var self=this,mod={},modalIsOpen=false,modalTrigger='.lbx-open.modal',$modalContent=$('<div/>').addClass('lbx-modal-content'),$modalMatte=$('<div/>').addClass('lbx-modal-matte');mod.init=function(){self.$overlayContent.on('click.lbx-modal-trigger',modalTrigger,mod.open);};mod.open=function(e){var $link=$(e.currentTarget),url=$link.attr('href');$modalMatte.appendTo(self.$overlay);self.$close.fadeOut('fast');mod.loadModalContent(url);if($link.data('full-width')=='1'){var $slide=$link.closest(".tie-slide.active");if($slide.length){$modalContent.css('width',$slide.width()+'px').addClass('full-width');}}
return false;};mod.loadModalContent=function(url,callback,$source){modalIsOpen=true;self.myOverlay.loadContent(url,$modalContent,function(data){$modalContent.prependTo(self.$overlayContent);$modalContent.on('click.lbx-modal','.lbx-modal-close',mod.close);$modalContent.on('submit.lbx-modal','#lbx-modal-form',mod.sendForm);$modalContent.on('keydown.lbx-modal',function(e){e.stopPropagation();});if(callback)callback(data);},$source);};mod.sendForm=function(){var $form=$('#lbx-modal-form'),url=$form.attr('action');$.post(url,$form.serialize(),function(data){$modalContent.html(data);if($(data).find('#download-file').length){$(data).find('#download-file')[0].click();mod.close();}});return false;};mod.close=function(){if(modalIsOpen===false){return;}
modalIsOpen=false;$modalMatte.remove();$modalContent.remove();self.$overlayContent.off('.lbx-modal');self.$close.fadeIn('fast');if(self.settings.closeOnModalClose){self.myOverlay.close();}
return false;};return{init:mod.init,close:mod.close,loadModalContent:mod.loadModalContent};};Lightbox.prototype.flyout=function(){var self=this,mod={},flyoutIsOpen=false,flyoutTrigger='.lbx-open.flyout',$flyoutWrapper=$('<div/>').addClass('lbx-flyout-wrapper'),$flyoutContent=$('<div/>').addClass('lbx-flyout-content').appendTo($flyoutWrapper),$flyoutClose=$('<div/>').addClass('lbx-close'),$parentSlide;mod.init=function(){self.$overlayContent.on('mousedown.lbx-flyout-trigger click.lbx-flyout-trigger',flyoutTrigger,mod.open);};mod.open=function(e){e.stopImmediatePropagation();var $link=$(e.currentTarget),url=$link.attr('href');$link.closest('.lbx-show-preloader').addClass('preloading');$parentSlide=$link.parents('.tie-slide');$flyoutWrapper.removeClass('closed');mod.loadFlyoutContent(url);flyoutIsOpen=true;return false;};mod.loadFlyoutContent=function(url){var $link=$(flyoutTrigger);$flyoutContent.hide();self.myOverlay.loadContent(url,$flyoutContent,function(){$flyoutWrapper.prependTo($parentSlide);$flyoutClose.appendTo($flyoutContent).one('click.lbx-flyout',mod.close);$link.closest('.lbx-show-preloader').removeClass('preloading');$flyoutContent.on('click.lbx-flyout','.lbx-modal-close',mod.close);$flyoutContent.fadeIn();});};mod.close=function(e){if(flyoutIsOpen===false){return;}
flyoutIsOpen=false;$flyoutContent.fadeOut();self.$overlayContent.off('.lbx-flyout');e.preventDefault();};return{init:mod.init,close:mod.close,};};$.lightbox=function(el,options){if(typeof options==='object'||!options){new Lightbox(el,options);}};window.USM=window.USM||{};$.lightbox.defaults={baseWidth:600,baseHeight:855,openImages:false,openModal:false,closeOnModalClose:false,openFlyout:false,closeOnBlur:false,openRichText:false,openDialog:false,dialogCloseTime:2000,lightboxTarget:$('body'),ajaxUrl:window.USM.lightbox_base||'ajax/lightbox-dev.html?'};$.lightbox('.lbx-open.images',{openImages:true});$.lightbox('.lbx-open.video',{openVideo:true});$.lightbox('.lbx-open.modal',{openModal:true,closeOnModalClose:true});$.lightbox('.lbx-open.flyout',{openFlyout:true});$.lightbox('.lbx-open.dialog',{openDialog:true});$.lightbox('.lbx-open.module-content',{openModal:true,closeOnModalClose:true,loadProductDetails:true});$.lightbox('a.lbx-open.richtext, .lbx-open.richtext a',{openRichText:true,closeOnBlur:true});});});