define(['./USM','jquery','jquery.cookie','django-ajax','./illuminate','./load-more-button','bigtext'],function(USM,$){'use strict';$(function(){if($.cookie('cookie-info')!=='closed'){$('body').prepend($('#cookie-snippet').text());}
$('body').on('click','.usm-cookie .close',function(e){e.preventDefault();$('.usm-cookie').remove();});$.cookie('cookie-info','closed',{'path':'/'});var $article=$('.mag-article'),$sidebar=$article.find('.rtf-info-right'),$articleFooter=$article.find('.lw-ft');var $tocItems=$article.find('.rtf-has-toc'),$tocList=$tocItems.first().parent().prepend('<div class="rtf-text-sidebar">'+'<div class="sidebar">'+'<div class="sidebar">'+'<ul class="rtf-list-jump"></ul>'+'</div>'+'</div>'+'<div class="text"></div>'+'</div>').find('.rtf-list-jump');$article.find('.rtf-text-sidebar .text').append($tocItems.first());$article.find('.rtf-has-toc').each(function(tocIndex){var $item=$(this);$item.find('h4').each(function(h4Index){var $this=$(this),id="toc-"+tocIndex+"-"+h4Index;$(this).attr('id',id);$tocList.append('<li><a class="rtf-jump jmp" href="#'+id+'">'+$this.text()+'</a></li>');});});$('.mag-header, .plt-header').bigtext({childSelector:'> h1',maxfontsize:200}).css('visibility','visible');if($sidebar.length){var footerHeight=0;if($articleFooter.length){footerHeight=$articleFooter.outerHeight();}
$article.find('.rtf').css('min-height',($sidebar.outerHeight()+footerHeight)+"px");}
var $upper_sidebar=$('.rtf-text-sidebar .sidebar');var $article=$('.mag-article');var $content=$('.mag-article .rtf');function adjust_upper_sidebar(){if($article.length&&$upper_sidebar.length&&$content.length){var top=0;if($(window).width()>766){top+=$content.offset().top-$article.offset().top;}
if($(window).width()>1020){top+=$upper_sidebar.height()+60;}
$sidebar.css({'margin-top':top+'px'});}}
adjust_upper_sidebar();$(window).resize(adjust_upper_sidebar);var $article=$('.mag-article'),$sidebar=$article.find('.rtf-info-right'),$articleFooter=$article.find('.lw-ft');if($sidebar.length){var footerHeight=0;if($articleFooter.length){footerHeight=$articleFooter.outerHeight();}
$article.find('.rtf').css('min-height',($sidebar.outerHeight()+footerHeight)+"px");}
$('.footer').show();$('.footer .toggle-mobile h4').click(function(){if($(window).width()<=USM.config.BP_SMARTPHONE_MAX){var $toggleParent=$(this).parents('.toggle-mobile');$toggleParent.toggleClass('open');$toggleParent.find('.list').slideToggle();return false;}});$('body').on('click','a[data-track]',function(ev){var $a=$(this),url=$a.data('track');if(url&&__gaTracker){var redirect=function(){location.href=$a.attr('href');}
__gaTracker('send','pageview',{'page':url,'hitCallback':redirect});setTimeout(redirect,1000);ev.preventDefault();}});});});