define(['jquery','./USM','jquery.touchSwipe'],function($,USM){'use strict';$(function(){var defaults={};var SwipeContent=function(el,options){var self=this;self.settings=$.extend({},defaults,options);self.triggerEl=el;self.$swp=$(el);self.$swpItems=self.$swp.find('.swp-items');self.$swpItem=self.$swp.find('.swp-item');self.$pagination=self.$swp.find('.pgn');self.$paginationNext=self.$pagination.find('.next');self.$paginationPrev=self.$pagination.find('.prev');self.$swpHeaderImage=self.$swp.find('.swp-items');self.pages=self.$swp.data('swp').replace(/\s/g,'').split(',');self.myEvents=$({});self.myPageManager=self.pageManager();self.myPageManager.init();window.USM=window.USM||{};self.track_urls={};self.track_urls[self.myPageManager.getCurrentPageId()]=window.USM.analytics_url;self.myPagination=self.pagination();self.myPagination.init();self.myAnalytics=self.analytics();self.myAnalytics.init();};SwipeContent.prototype.pagination=function(){var self=this,mod={};mod.init=function(){self.myEvents.bind('pageChange',mod.updatePagination);self.$paginationNext.on('click',self.myPageManager.gotoNext);self.$paginationPrev.on('click',self.myPageManager.gotoPrev);self.$swpItems.on('click','.swp-item.next',self.myPageManager.gotoNext);mod.updatePagination();};mod.validateId=function(id){if(typeof id==='number'&&id>=0&&id<self.pages.length){return id;}else{return false;}};mod.updatePagination=function(){var pages=self.pages,currId=self.myPageManager.getCurrentPageId(),prevId=mod.validateId(currId-1),nextId=mod.validateId(currId+1);if(nextId!==false){self.$paginationNext.removeClass('disabled').attr('href',pages[nextId]);}else{self.$paginationNext.addClass('disabled').removeAttr('href');}
if(prevId!==false){self.$paginationPrev.removeClass('disabled').attr('href',pages[prevId]);}else{self.$paginationPrev.addClass('disabled').removeAttr('href');}};return{init:mod.init};};SwipeContent.prototype.analytics=function(){var self=this,mod={},timeThreshold=2000,timer;mod.init=function(){self.myEvents.bind('pageChange',mod.manageTimeout);};mod.manageTimeout=function(){clearTimeout(timer);timer=setTimeout(mod.track,timeThreshold);};mod.track=function(){var currentPageId=self.myPageManager.getCurrentPageId(),url=self.track_urls[currentPageId];if(url&&url!==''){__gaTracker('set','page',url);__gaTracker('send','pageview');}};return{init:mod.init};};SwipeContent.prototype.pageManager=function(){var self=this,mod={},pages=self.pages,location=window.location.pathname,locationPath=function(){var path=window.location.pathname.split('/');path.pop();path.shift();path=path.join('/');return'/'+path;},pathExtLive='?ajax=true',pathExtLocal='ajax',isLocal=false,currPageId=0,initPageId=0,lastPageId=0,loadedPages=[],$loadedPages=[],setLoadedPage=function(id){loadedPages[id]=true;},cssTransform=Modernizr.prefixed('transform');mod.init=function(){if(self.$swp.data('swp-local')){isLocal=true;}
currPageId=mod.getPageId();initPageId=currPageId;loadedPages=new Array(pages.length-1);$loadedPages=new Array(pages.length-1);$loadedPages[currPageId]=self.$swpItem.first();setLoadedPage(currPageId);self.$swpItem.first().addClass('active');mod.getPage(currPageId+1);$(document).keydown(function(e){switch(e.which){case 37:mod.gotoPrev();break;case 39:mod.gotoNext();break;default:return;}});};mod.gotoNext=function(){mod.gotoPage(currPageId+1);return false;};mod.gotoPrev=function(){mod.gotoPage(currPageId-1);return false;};mod.gotoPage=function(id){console.log('gotoPage');var isTransitionEnd=false,relativeIndex=mod.getRelativeIndex(id),gotoPos=relativeIndex*-100+'%';if(relativeIndex===false){return;}
$('.on-render-tree').removeClass('on-render-tree');lastPageId=currPageId;currPageId=id;var newURL=mod.updateHistory();if(Modernizr.csstransforms3d&&Modernizr.csstransitions){console.log('modern browsers');self.$swpItems.css(cssTransform,'translateX('+gotoPos+')').on('transitionend webkitTransitionEnd oTransitionEnd otransitionend',function(){if(!isTransitionEnd){if(!loadedPages[id]){mod.getPage(id);}
if(!loadedPages[id+1]&&id+1<pages.length){mod.getPage(id+1);}
mod.setClasses();isTransitionEnd=true;}});}else{console.log('fallback');var percWidth=Math.round(100/self.$swp.width()*self.$swpItems.width());gotoPos=relativeIndex*-percWidth+'%';self.$swpItems.animate({'left':gotoPos},function(){if(!loadedPages[id]){mod.getPage(id);}
if(!loadedPages[id+1]&&id+1<pages.length){mod.getPage(id+1);}
mod.setClasses();});}
var $subnavItems=$('.nav-main-sub .nav-item a');var $activeSubnavItem=$subnavItems.filter(function(index){return newURL.indexOf($(this).attr('href'))>=0;});if($activeSubnavItem.length){$subnavItems.removeClass('active');$activeSubnavItem.addClass('active');}
self.myEvents.trigger('pageChange');console.log('trigger pageChange');return false;};mod.setClasses=function(){if(!$loadedPages[currPageId]){return;}
var $all=self.$swpItems.children(),$active=$loadedPages[currPageId],$next=$active.next(),$prev=$active.prev();$all.removeClass('active next prev off').addClass('off');$active.addClass('active').removeClass('off');$next.addClass('next').removeClass('off');$prev.addClass('prev').removeClass('off');var favId=$active.find('.csw-items a.active').attr('data-favorites-id');$('.fav-btn').attr('data-favorites-id',favId);if($active.find('.frl').length!==0){var dom=$active;require(['app/flick-reel'],function(){var elementMorphing=dom.find('.frl.isMorphing');elementMorphing.FlickReel({keyframeCtrl:true,sliderSnapToKeyframe:true});dom.find('.frl.isAnimation').FlickReel({slider:false});var button=dom.find('.frl.isMorphing').find('#frl-btn');if(elementMorphing.hasClass('no-autoplay')==true){button.remove();}else if(button.hasClass('frl-play-btn')){button.toggleClass("frl-play-btn").toggleClass("frl-pause-btn");}});}};mod.getRelativeIndex=function(id){if(typeof id==='number'&&id>=0&&id<pages.length){return id-initPageId;}else{return false;}};mod.addPage=function($data,id){var $newPage=$('<div/>').addClass('swp-item next'),relativeId=mod.getRelativeIndex(id),pagePos;pagePos=relativeId*100+'%';$newPage.css('left',pagePos).append($data);$loadedPages[id]=$newPage;if(id<lastPageId){$newPage.prependTo(self.$swpItems);}else{$newPage.appendTo(self.$swpItems);}
mod.setClasses();this.initAgain($newPage);};mod.getPageId=function(){var locPath=locationPath(),i=0,currId;while(!currId&&i<pages.length){var locThis=location,locThat=pages[i];if(isLocal&&!window.location.port){locThat=locPath+pages[i];}
if(locThis===locThat){return i;}
i++;}};mod.getPage=function(id,prev,callback){if(id!==undefined){if(loadedPages[id]!==true&&id>=0&&id<pages.length){loadedPages[id]=true;$.ajax({url:mod.buildAjaxUrl(pages[id])}).done(function(data,status,xhr){mod.addPage(data,id);var track_url=xhr.getResponseHeader('Tracking-URL');if(track_url&&track_url!==''){self.track_urls[id]=track_url;}
if(callback&&typeof callback==='function'){callback();}});}else{if(callback&&typeof callback==='function'){callback();}}}else{throw new Error("getPage(): missing id argument");}};mod.buildAjaxUrl=function(url){if(isLocal){return pathExtLocal+url;}else{return url+pathExtLive;}};mod.updateHistory=function(){if(!Modernizr.history){return;}
var isLocal=self.myPageManager.isLocal();var port=window.location.port?':'+window.location.port:'';var hostOrigin=window.location.protocol+"//"+window.location.hostname+port;var newUrl=hostOrigin+pages[currPageId];if(isLocal&&!window.location.port){newUrl=hostOrigin+locationPath()+pages[currPageId];}
history.pushState('','',newUrl);return pages[currPageId];};mod.initAgain=function(dom){if(dom.find('.frl.is360').length!==0){require(['app/flick-reel'],function(){dom.find('.frl.is360').FlickReel({preloadOnLoad:false});});}
if(dom.find('.stg-hotspots').length!==0){require(['app/hotspots'],function(){dom.find('.stg-hotspots').hotspots();});}
if(dom.find('.phu-tgl').length!==0){require(['app/toggle-phu'],function(){dom.find('.phu-tgl').tglProductHero();});}
if(dom.find('.drp').length!==0){require(['app/drop-down'],function(){dom.find('.drp').productDropDown();});}
if(dom.find('.szm').length!==0){require(['app/super-zoom'],function(){dom.find('.szm').superZoom();});}
if(dom.find('.acc').length!==0){require(['app/accordion'],function(){$('.acc').accordion();});}
if(dom.find('.csw').length!==0){require(['app/color-switcher'],function(){dom.find('.csw').colorSwitcher();});}
if(dom.find('.phu.shop').length!==0){require(['app/ctrl-shop-unit'],function(){dom.find('.phu.shop').shopUnit();});}
if(!$.favorites){require(['app/favorites']);}else{$(USM.events).trigger('FAV_UPDATEBUTTON');}
if(dom.find('.jQ-more-images').length!==0){require(['app/more-images'],function(){dom.find('.jQ-more-images').moreImages();});}
if(dom.find('.shr').length!==0){require(['app/social-share'],function(){dom.find('.shr').socialShare();});}
if(dom.find('.msl').length!==0){require(['app/msl-module-select'],function(){dom.find('.msl').moduleSelect();});}
if(dom.find('.rib.product').length!==0){require(['app/ribbons'],function(){USM.ribbon.product.init();});}
if(!$.lightbox){require(['app/lightboxes']);}};return{init:mod.init,gotoNext:mod.gotoNext,gotoPrev:mod.gotoPrev,isLocal:function(){return isLocal;},getCurrentPageId:function(){return currPageId;}};};$.fn.swipeContent=function(options){this.each(function(){if(!$.data(this,'plugin_swipeContent')){$.data(this,'plugin_swipeContent',new SwipeContent(this,options));}});return this;};$('#swp').swipeContent();});});